version: "3.8"

services:
  calendiary-db:
    image: postgres:latest                     # Use the latest official PostgreSQL image
    container_name: calendiary-db                   # Set a custom name for the container
    ports:
      - "5433:5432"                            # Map container port 5433 to host port 5432
      # If port 5432 is busy, change to "5433:5432"
    volumes:
      - db_data_1:/var/lib/postgresql/data     # Persist database data between container restarts
    environment:
      POSTGRES_USER: postgres                     # Username for the PostgreSQL database
      POSTGRES_PASSWORD: ´yourpassword´                  # Password for the database user
      POSTGRES_DB: calendiary                    # Name of the database to create on container startup

volumes:
  db_data_1:                                    # Define a named volume to store PostgreSQL data




