server:
  port: 8080

spring:
  datasource:
    #url: jdbc:postgresql://localhost:5432/calendiary
    url: jdbc:postgresql://localhost:5433/calendiary
    username: postgres
    password: ´yourpassword´
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# SpringDoc OpenAPI (Swagger)
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha