server:
  port: 8080

spring:
  datasource:
    #url: jdbc:postgresql://localhost:5432/calendiary
    url: jdbc:postgresql://localhost:5433/calendiary
    username: postgres
    password: ´yourpassword´
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration #no credentials on 8080 login

# SpringDoc OpenAPI (Swagger)
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

jwt:
  secret: your-256-bit-secret-key-must-be-at-least-32-chars-long
  issuer: "auth-backend"

auth:
  service:
      base-url: http://your-colleagues-auth-backend:8080 # Get this from your colleague